apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_USER: bGFidXNlcg==
  POSTGRES_PASSWORD: bGFicGFzc3dvcmQ=
  POSTGRES_DB: bGFiZGI=
  DB_USER: bGFidXNlcg==
  DB_PASSWORD: bGFicGFzc3dvcmQ=
  DB_NAME: bGFiZGI=

